ARI: 
 location: Arizona 
 name: Cardinals
 logo: https://upload.wikimedia.org/wikipedia/en/7/72/Arizona_Cardinals_logo.svg
 city: Glendale
 state: AZ
 dome: True
 color: "#97233F"


ATL:
 location: Atlanta 
 name: Falcons
 logo: https://upload.wikimedia.org/wikipedia/en/c/c5/Atlanta_Falcons_logo.svg
 city: Atlanta
 state: GA
 dome: True
 color: "#A71930"

BAL:
 location: Baltimore  
 name: Ravens
 logo: https://upload.wikimedia.org/wikipedia/en/1/16/Baltimore_Ravens_logo.svg
 city: Baltimore
 state: MD
 dome: False
 color: "#241773"

BUF:
 location: Buffalo  
 name: Bills
 logo: https://upload.wikimedia.org/wikipedia/en/7/77/Buffalo_Bills_logo.svg
 city: Orchard Park
 state: NY
 dome: False
 color: "#00338D"

CAR:
 location: Carolina  
 name: Panthers
 logo: https://upload.wikimedia.org/wikipedia/en/1/1c/Carolina_Panthers_logo.svg
 city: Charlotte
 state: NC
 dome: False
 color: "#0085CA"

CHI:
 location: Chicago  
 name: Bears
 logo: https://upload.wikimedia.org/wikipedia/commons/5/5c/Chicago_Bears_logo.svg
 city: Chicago
 state: IL
 dome: False
 color: "#C83803"

CIN:
 location: Cincinnati  
 name: Bengals
 logo: https://upload.wikimedia.org/wikipedia/commons/8/81/Cincinnati_Bengals_logo.svg
 city: Cincinnati
 state: OH
 dome: False
 color: "#FB4F14"

CLE:
 location: Cleveland  
 name: Browns
 logo: https://upload.wikimedia.org/wikipedia/en/d/d9/Cleveland_Browns_logo.svg
 city: Cleveland
 state: OH
 dome: False
 color: "#FF3C00"

DAL:
 location: Dallas  
 name: Cowboys
 logo: https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg
 city: Arlington
 state: TX
 dome: True
 color: "#003594"

DEN:
 location: Denver  
 name: Broncos
 logo: https://upload.wikimedia.org/wikipedia/en/4/44/Denver_Broncos_logo.svg
 city: Denver
 state: CO
 dome: False
 color: "#FB4F14"

DET:
 location: Detroit  
 name: Lions
 logo: https://upload.wikimedia.org/wikipedia/en/7/71/Detroit_Lions_logo.svg
 city: Detroit
 state: MI
 dome: True
 color: "#0076B6"

GB:
 location: Green Bay  
 name: Packers
 logo: https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg
 city: Green Bay
 state: WI
 dome: False
 color: "#203731"

HOU:
 location: Houston  
 name: Texans
 logo: https://upload.wikimedia.org/wikipedia/en/2/28/Houston_Texans_logo.svg
 city: Houston
 state: TX
 dome: True
 color: "#03202F"

IND:
 location: Indianapolis  
 name: Colts
 logo: https://upload.wikimedia.org/wikipedia/commons/0/00/Indianapolis_Colts_logo.svg
 city: Indianapolis
 state: IN
 dome: True
 color: "#002C5F"

JAX:
 location: Jacksonville  
 name: Jaguars
 logo: https://upload.wikimedia.org/wikipedia/en/7/74/Jacksonville_Jaguars_logo.svg
 city: Jacksonville
 state: FL
 dome: False
 color: "#006778"

KC:
 location: Kansas City  
 name: Chiefs
 logo: https://upload.wikimedia.org/wikipedia/en/e/e1/Kansas_City_Chiefs_logo.svg
 city: Kansas City
 state: MO
 dome: False
 color: "#E31837"

LV:
 location: Las Vegas  
 name: Raiders
 logo: https://upload.wikimedia.org/wikipedia/en/6/6a/Las_Vegas_Raiders_logo.svg
 city: Paradise
 state: NV
 dome: True
 color: "#A5ACAF"

LAC:
 location: Los Angeles  
 name: Chargers
 logo: https://upload.wikimedia.org/wikipedia/en/7/72/Los_Angeles_Chargers_logo.svg
 city: Inglewood
 state: CA
 dome: False
 color: "#0073CF"

LA:
 location: Los Angeles  
 name: Rams
 logo: https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg
 city: Inglewood
 state: CA
 dome: False
 color: "#003594"

MIA:
 location: Miami  
 name: Dolphins
 logo: https://upload.wikimedia.org/wikipedia/en/3/37/Miami_Dolphins_logo.svg
 city: Miami
 state: FL
 dome: False
 color: "#008E97"

MIN:
 location: Minnesota  
 name: Vikings
 logo: https://upload.wikimedia.org/wikipedia/en/4/48/Minnesota_Vikings_logo.svg
 city: Minneapolis
 state: MN
 dome: True
 color: "#4F2683"

NE:
 location: New England  
 name: Patriots
 logo: https://upload.wikimedia.org/wikipedia/en/b/b9/New_England_Patriots_logo.svg
 city: Foxborough 
 state: MA
 dome: False
 color: "#002244"

'NO':
 location: New Orleans  
 name: Saints
 logo: https://upload.wikimedia.org/wikipedia/commons/5/50/New_Orleans_Saints_logo.svg
 city: New Orleans
 state: LA
 dome: True
 color: "#D3BC8D"

NYG:
 location: New York  
 name: Giants
 logo: https://upload.wikimedia.org/wikipedia/commons/6/60/New_York_Giants_logo.svg
 city: East Rutherford
 state: NJ
 dome: False
 color: "#0B2265"

NYJ:
 location: New York  
 name: Jets
 logo: https://upload.wikimedia.org/wikipedia/en/6/6b/New_York_Jets_logo.svg
 city: East Rutherford
 state: NJ
 dome: False
 color: "#125740"

PHI:
 location: Philadelphia  
 name: Eagles
 logo: https://upload.wikimedia.org/wikipedia/en/8/8e/Philadelphia_Eagles_logo.svg
 city: Philadelphia
 state: PA
 dome: False
 color: "#004C54"

PIT:
 location: Pittsburgh  
 name: Steelers
 logo: https://upload.wikimedia.org/wikipedia/commons/d/de/Pittsburgh_Steelers_logo.svg
 city: Pittsburgh
 state: PA
 dome: False
 color: "#FFB612"

SF:
 location: San Francisco  
 name: 49ers
 logo: https://upload.wikimedia.org/wikipedia/commons/3/3b/San_Francisco_49ers_logo.svg
 city: Santa Clara
 state: CA
 dome: False
 color: "#AA0000"

SEA:
 location: Seattle  
 name: Seahawks
 logo: https://upload.wikimedia.org/wikipedia/en/8/8e/Seattle_Seahawks_logo.svg
 city: Seattle
 state: WA
 dome: False
 color: "#002244"

TB:
 location: Tampa Bay  
 name: Buccaneers
 logo: https://upload.wikimedia.org/wikipedia/en/a/a2/Tampa_Bay_Buccaneers_logo.svg
 city: Tampa
 state: FL
 dome: False
 color: "#D50A0A"

TEN:
 location: Tennessee  
 name: Titans
 logo: https://upload.wikimedia.org/wikipedia/en/c/c1/Tennessee_Titans_logo.svg
 city: Nashville
 state: TN
 dome: False
 color: "#4B92DB"

WAS:
 location: Washington  
 name: Commanders
 logo: https://upload.wikimedia.org/wikipedia/commons/8/89/Washington_Commanders_logo.svg
 city: Landover
 state: MD
 dome: False
 color: "#773141"